"use client";

import { useState } from "react";
import { customers, inventory, quotes } from "@/features/records/mock-data";

export type QuickSection = "home" | "list" | "inventory" | "quotes" | "search" | "export" | "dashboard";

const features: Array<{ id: QuickSection; label: string; description: string; icon: string; tone: string }> = [
  { id: "list", label: "廠家", description: "查看與新增廠家", icon: "店", tone: "bg-emerald-50 text-emerald-700" },
  { id: "inventory", label: "樣品庫存", description: "簡易盤點庫存", icon: "庫", tone: "bg-amber-50 text-amber-700" },
  { id: "quotes", label: "報價單", description: "查看廠家報價", icon: "價", tone: "bg-sky-50 text-sky-700" },
  { id: "search", label: "搜尋", description: "快速找店家資料", icon: "搜", tone: "bg-violet-50 text-violet-700" },
  { id: "export", label: "匯出", description: "客戶與報價 Excel", icon: "出", tone: "bg-slate-100 text-slate-700" },
  { id: "dashboard", label: "儀表板", description: "查看業務進度", icon: "表", tone: "bg-rose-50 text-rose-700" },
];

export function QuickHomeContent({ onNavigate, onCreate, canCreate }: { onNavigate: (section: QuickSection) => void; onCreate: () => void; canCreate: boolean }) {
  return <main className="flex-1 px-5 pb-28 pt-20"><p className="text-sm font-medium text-[#286533]">PIN CHAU CDS</p><h1 className="mt-2 text-3xl font-bold tracking-tight text-[#252521]">今天要做什麼？</h1><p className="mt-2 text-sm text-[#777269]">外勤快速建檔，回公司後再由後台補齊資料。</p><button type="button" disabled={!canCreate} onClick={onCreate} className="mt-7 flex w-full items-center gap-4 rounded-2xl bg-[#286533] p-5 text-left text-white shadow-lg shadow-[#286533]/20 transition active:scale-[0.99] disabled:cursor-not-allowed disabled:opacity-45"><span className="flex size-14 shrink-0 items-center justify-center rounded-full bg-white/15 text-4xl font-light">＋</span><span><span className="block text-xl font-bold">{canCreate ? "快速建檔" : "唯讀模式"}</span><span className="mt-1 block text-sm text-white/70">{canCreate ? "店名、聯絡人、樣品、照片與備註" : "此角色不可新增或編輯資料"}</span></span><span className="ml-auto text-2xl text-white/60">›</span></button><section className="mt-8"><div className="mb-3 flex items-center justify-between"><h2 className="font-bold text-[#323129]">主功能</h2><span className="text-xs text-[#8b877d]">介面模板</span></div><div className="grid grid-cols-2 gap-3">{features.map((feature) => <button key={feature.id} type="button" onClick={() => onNavigate(feature.id)} className="rounded-2xl border border-[#ded3bb] bg-[#fffdf8] p-4 text-left shadow-sm transition hover:-translate-y-0.5"><span className={`flex size-10 items-center justify-center rounded-xl text-sm font-bold ${feature.tone}`}>{feature.icon}</span><span className="mt-4 block font-bold text-[#333129]">{feature.label}</span><span className="mt-1 block text-xs text-[#8b877d]">{feature.description}</span></button>)}</div></section></main>;
}

export function QuickInventoryContent() {
  const categories = ["茶葉", "茶包", "調味茶", "特殊OEM/其他"];
  const tones: Record<string, string> = { 茶葉: "bg-emerald-50 text-emerald-700", 茶包: "bg-amber-50 text-amber-800", 調味茶: "bg-pink-50 text-pink-700", "特殊OEM/其他": "bg-violet-50 text-violet-700" };
  return <main className="flex-1 space-y-5 p-4 pb-24">{categories.map((category) => <section key={category} className="overflow-hidden rounded-xl border border-[#d8c9a9] bg-[#fffdf8]"><div className="flex items-center justify-between bg-[#f6f1e8] px-4 py-3"><h2 className="font-bold text-[#37352f]">{category}</h2><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${tones[category]}`}>{inventory.filter((item) => item.category === category).length} 項</span></div><div className="divide-y divide-[#eee7d9]">{inventory.filter((item) => item.category === category).map((item) => <div key={item.name} className="flex items-center justify-between gap-3 px-4 py-3"><div><p className="text-sm font-medium text-[#36342f]">{item.name}</p><p className="mt-1 text-xs text-[#938e83]">{item.location}{item.note ? ` · ${item.note}` : ""}</p></div><span className={`text-sm font-bold ${item.qty <= 5 ? "text-rose-600" : "text-[#286533]"}`}>{item.qty} {item.unit}</span></div>)}</div></section>)}</main>;
}

export function QuickQuotesContent() {
  return <main className="flex-1 space-y-4 p-4 pb-24">{quotes.map((quote) => { const customer = customers.find((item) => item.id === quote.customerId); const total = quote.items.reduce((sum, item) => sum + item.qty * item.price, 0); return <article key={quote.id} className="rounded-xl border border-[#d8c9a9] bg-[#fffdf8] p-4 shadow-sm"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold text-[#286533]">{quote.number}</p><h2 className="mt-1 font-bold text-[#34322d]">{customer?.name}</h2></div><span className="rounded-full bg-[#f0e7d7] px-3 py-1 text-xs text-[#765f39]">{quote.status}</span></div><div className="mt-4 space-y-3">{quote.items.map((item) => <div key={item.name} className="grid grid-cols-[44px_1fr_auto] items-center gap-3 rounded-xl bg-[#f6f1e8] p-3"><div className="flex size-11 items-center justify-center rounded-lg bg-[#dfeadd] text-lg">茶</div><div><p className="text-sm font-semibold text-[#3a3831]">{item.name}</p><p className="mt-1 text-xs text-[#8b877d]">{item.spec} · {item.unit} · 數量 {item.qty}</p></div><p className="text-sm font-bold text-[#286533]">${item.price.toLocaleString()}</p></div>)}</div><div className="mt-4 flex justify-between border-t border-[#eee7d9] pt-3 text-sm"><span className="text-[#777269]">報價合計</span><strong className="text-lg text-[#2c2a25]">${total.toLocaleString()}</strong></div></article>; })}</main>;
}

export function QuickSearchContent() {
  const [query, setQuery] = useState("");
  const [region, setRegion] = useState("");
  const [sample, setSample] = useState("");
  const [status, setStatus] = useState("");
  const regions = [...new Set(customers.map((customer) => customer.region))];
  const samples = [...new Set(customers.flatMap((customer) => customer.samples))];
  const statuses = [...new Set(customers.map((customer) => customer.status))];
  const results = customers.filter((customer) => {
    const matchesQuery = !query.trim() || [customer.name, customer.contact, customer.phone, customer.region, customer.status, ...customer.samples].some((value) => value.toLowerCase().includes(query.trim().toLowerCase()));
    return matchesQuery && (!region || customer.region === region) && (!sample || customer.samples.includes(sample)) && (!status || customer.status === status);
  });
  return <main className="flex-1 p-4 pb-24"><input value={query} onChange={(event) => setQuery(event.target.value)} autoFocus placeholder="自由搜尋區域、樣品或狀態" className="w-full rounded-xl border border-[#cfbd95] bg-white px-4 py-3 outline-none focus:border-[#286533]" /><div className="mt-3 grid grid-cols-3 gap-2"><select value={region} onChange={(event) => setRegion(event.target.value)} className="min-w-0 rounded-lg border border-[#d8c9a9] bg-white px-2 py-2 text-xs"><option value="">全部區域</option>{regions.map((item) => <option key={item}>{item}</option>)}</select><select value={sample} onChange={(event) => setSample(event.target.value)} className="min-w-0 rounded-lg border border-[#d8c9a9] bg-white px-2 py-2 text-xs"><option value="">全部樣品</option>{samples.map((item) => <option key={item}>{item}</option>)}</select><select value={status} onChange={(event) => setStatus(event.target.value)} className="min-w-0 rounded-lg border border-[#d8c9a9] bg-white px-2 py-2 text-xs"><option value="">全部狀態</option>{statuses.map((item) => <option key={item}>{item}</option>)}</select></div><p className="mt-4 text-xs text-[#8b877d]">找到 {results.length} 家廠家</p><div className="mt-3 space-y-3">{results.map((customer) => <article key={customer.id} className="rounded-xl border border-[#ded3bb] bg-[#fffdf8] p-4"><div className="flex justify-between gap-3"><div><h2 className="font-bold text-[#34322d]">{customer.name}</h2><p className="mt-1 text-sm text-[#777269]">{customer.contact} · {customer.phone}</p><p className="mt-2 text-xs text-[#8b877d]">{customer.samples.join("、")}</p></div><div className="flex flex-col items-end gap-2"><span className="h-fit rounded-full bg-[#286533] px-3 py-1 text-xs text-white">{customer.region}</span><span className="text-xs text-[#8a6518]">{customer.status}</span></div></div></article>)}</div></main>;
}

export function QuickExportContent() {
  const [message, setMessage] = useState("");
  return <main className="flex-1 space-y-4 p-4 pb-24">{message && <div className="rounded-xl bg-emerald-50 p-3 text-center text-sm text-emerald-700">{message}</div>}<div className="rounded-xl border border-[#d8c9a9] bg-[#fffdf8] p-5"><span className="flex size-12 items-center justify-center rounded-xl bg-emerald-50 font-bold text-emerald-700">ALL</span><h2 className="mt-4 font-bold text-[#34322d]">廠家總資訊匯出</h2><p className="mt-1 text-sm leading-6 text-[#777269]">匯出所有廠家基本資料、商業價值與追蹤狀態。</p><div className="mt-4 grid grid-cols-2 gap-2"><button type="button" onClick={() => setMessage("CSV 匯出介面已確認，正式資料接通後啟用下載。") } className="rounded-xl border border-emerald-200 bg-emerald-50 py-3 text-sm font-semibold text-emerald-700">CSV</button><button type="button" onClick={() => setMessage("Excel 匯出介面已確認，正式資料接通後啟用下載。") } className="rounded-xl bg-emerald-700 py-3 text-sm font-semibold text-white">Excel</button></div></div><div className="rounded-xl border border-[#d8c9a9] bg-[#fffdf8] p-5"><span className="flex size-12 items-center justify-center rounded-xl bg-sky-50 font-bold text-sky-700">QT</span><h2 className="mt-4 font-bold text-[#34322d]">個別廠家報價單</h2><p className="mt-1 text-sm leading-6 text-[#777269]">選擇廠家後匯出該廠商的報價資訊與品項。</p><select className="mt-4 w-full rounded-xl border border-[#d8c9a9] bg-white px-4 py-3 text-sm">{customers.map((customer) => <option key={customer.id}>{customer.name}</option>)}</select><div className="mt-3 grid grid-cols-2 gap-2"><button type="button" onClick={() => setMessage("PDF 報價匯出介面已確認，正式資料接通後啟用下載。") } className="rounded-xl border border-sky-200 bg-sky-50 py-3 text-sm font-semibold text-sky-700">PDF</button><button type="button" onClick={() => setMessage("Excel 報價匯出介面已確認，正式資料接通後啟用下載。") } className="rounded-xl bg-sky-700 py-3 text-sm font-semibold text-white">Excel</button></div></div></main>;
}

export function QuickDashboardContent() {
  const now = new Date();
  const month = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}`;
  const stats = [["客戶總數", customers.length], ["本月新增", customers.filter((item) => item.createdAt.startsWith(month)).length], ["本月成交", customers.filter((item) => item.closedAt?.startsWith(month)).length], ["待追蹤", customers.filter((item) => item.nextFollow && item.status !== "已成交").length], ["待送樣", customers.filter((item) => item.status === "寄樣試用中").length], ["待報價", customers.filter((item) => item.status === "報價談判中").length], ["本週重要", customers.filter((item) => item.grade === "A" && item.status !== "已成交").length]] as const;
  const visualGroups = [["區域", [...new Set(customers.map((item) => item.region))].map((label) => [label, customers.filter((item) => item.region === label).length] as const)], ["開發狀態", [...new Set(customers.map((item) => item.status))].map((label) => [label, customers.filter((item) => item.status === label).length] as const)], ["競品茶商", [...new Set(customers.flatMap((item) => item.competitors))].map((label) => [label, customers.filter((item) => item.competitors.includes(label)).length] as const)], ["客戶類型", [...new Set(customers.map((item) => item.type))].map((label) => [label, customers.filter((item) => item.type === label).length] as const)]] as const;
  return <main className="flex-1 p-4 pb-24"><div className="grid grid-cols-2 gap-3">{stats.map(([label, value]) => <article key={label} className="rounded-xl border border-[#d8c9a9] bg-[#fffdf8] p-4"><p className="text-xs text-[#777269]">{label}</p><p className="mt-3 text-3xl font-bold text-[#286533]">{value}</p></article>)}</div><div className="mt-5 space-y-4">{visualGroups.map(([title, items]) => <section key={title} className="rounded-xl border border-[#d8c9a9] bg-[#f6f1e8] p-4"><h2 className="font-bold text-[#34322d]">{title}分布</h2><div className="mt-3 space-y-2">{items.map(([label, count]) => <div key={label} className="flex items-center gap-3 text-sm"><span className="w-24 truncate text-[#777269]">{label}</span><div className="h-2 flex-1 overflow-hidden rounded-full bg-white"><div className="h-full rounded-full bg-[#286533]" style={{ width: `${Math.max((count / customers.length) * 100, 5)}%` }} /></div><strong className="w-5 text-right">{count}</strong></div>)}</div></section>)}</div></main>;
}
